version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        container_name: openbrief-app
        ports:
            - '8000:8000'
        env_file:
            - .env.production
        environment:
            NODE_ENV: production
        restart: unless-stopped
